# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
    ENV["SLACK_CHANNEL"] = "#ios"
  end

  lane :test do
    run_tests(
      buildlog_path: "./fastlane/fastlane-buildlog",
      derived_data_path: "~/Library/Developer/Xcode/DerivedData",
      workspace: "PMS.xcworkspace",
      scheme: "PMSTests")
  end

  lane :github do
    create_keychain(
      name: "ios_app_store",
      password: "1234",
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true,
    )
    match(type: "appstore", readonly: true, keychain_name: 'ios_app_store', keychain_password: '1234')
    increment_build_number
    build_app(workspace: "PMS.xcworkspace", scheme: "PMS")
    upload_to_app_store(
      force: true,
      skip_metadata: true,
      skip_screenshots: true,
      skip_binary_upload: true
    )
  end

  lane :screenshots do 
    capture_screenshots(
	reinstall_app: true,
	clean: true)
  end
end
