# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  lane :test do
    run_tests(
      buildlog_path: "./fastlane/fastlane-buildlog",
      derived_data_path: "~/Library/Developer/Xcode/DerivedData",
      workspace: "PMS.xcworkspace",
      scheme: "PMSTests")
  end

  lane :coverage do
    slather(
      output_directory: "./fastlane/coverage",
      workspace: "PMS.xcworkspace",
      html: true,
      binary_basename: "PMS",
      scheme: "PMSTests",
      proj: "PMS.xcodeproj"
  )
  end

  lane :versionup do
    increment_build_number
  end

  lane :github do
    create_keychain(
      name: "ios_app_store",
      password: "1234",
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true,
    )
    match(type: "appstore", readonly: true, keychain_name: 'ios_app_store', keychain_password: '1234')
    build_app(workspace: "PMS.xcworkspace", scheme: "PMS")
    upload_to_app_store(force: true)
  end
  
  lane :release do
    increment_build_number
    build_app(workspace: "PMS.xcworkspace", scheme: "PMS")
    upload_to_app_store
    sh "watchbuild"
  end

  lane :screenshots do 
    capture_screenshots 
    upload_to_app_store 
  end
end
