# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  lane :test do
    run_tests(
      buildlog_path: "./fastlane/fastlane-buildlog",
      derived_data_path: "~/Library/Developer/Xcode/DerivedData",
      workspace: "PMS.xcworkspace",
      scheme: "PMSTests")
  end

  lane :coverage do
    slather(
      output_directory: "./fastlane/coverage",
      workspace: "PMS.xcworkspace",
      html: true,
      binary_basename: "PMS",
      scheme: "PMSTests",
      proj: "PMS.xcodeproj"
  )
  end

  lane :version do 
    increment_build_number(xcodeproj: 'PMS.xcodeproj')
  end

  lane :github do
    create_keychain(
      name: 'ios_app_keychain',
      password: '1234',
      Timeout: 1800,
      default_keychain: true,
      unlock: true,
      lock_when_sleeps: false
    )

    import_certificate(
      certificate_path 'distribution.p12',
      certificate_password: '1234',
      keychain_name: 'ios_app_keychain',
      keychain_password: '1234'
    )
    install_provisioning_profile(path: 'distribution.mobildprovision')
    update_project_provisioning(
      xcodeproj: 'PMS.xcodeproj',
      target_filter: 'github',
      profile: 'distrribution.mobileprovision',
      build_configuration: 'Release'
    )
    api_key = app_storre_connect_api_key(
      key_id: '5F84GBFHDC',
      issuer_id: '69a6de96-accd-47e3-e053-5b8c7c11a4d1',
      key_filepath: 'distribution.p8'
    )

    build_app(workspace: 'PMS.xcworkspace', scheme: 'PMS')
    upload_to_app_store(
      precheck_include_in_app_purchases: false,
      api_key: api_key
    )
  end
  
  lane :release do
    increment_build_number
    build_app(workspace: 'PMS.xcworkspace', scheme: 'PMS')
    upload_to_app_store
  end

  lane :screenshots do 
    capture_screenshots 
    upload_to_app_store 
  end
end
