name: Publish iOS App to App Store

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  release-ios:
    name: Build and release iOS app
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: submodules-init
        uses: snickerbockers/submodules-init@v4
      - name: Bundle Install
        run: bundle install
      - name: Set Appstore Connect User
        run: bundle exec fastlane fastlane-credentials add --username ${{ secrets.APPSTORE_USERNAME }} --password ${{ secrets.APPSTORE_PASSWORD }}
      - name: Increase Build Version
        run: bunddle exec fastlane versionup
      - name: Deploy App
        run: bundle exec fastlane github
